export const SOCKET_EVENTS = {
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  JOIN_USER: 'join_user',
  JOIN_RESCUE: 'join_rescue',
  LEAVE_RESCUE: 'leave_rescue',
  RESCUE_CREATED: 'rescue:created',
  RESCUE_UPDATED: 'rescue:updated',
  RESCUE_STATUS_UPDATED: 'rescue:status_updated',
  RESCUE_CLAIMED: 'rescue:claimed',
  RESCUE_ASSIGNED: 'rescue:assigned',
  RESCUE_ESCALATED: 'rescue:escalated',
  TIMELINE_EVENT: 'timeline:event',
  CHAT_MESSAGE_SEND: 'chat:message_send',
  CHAT_MESSAGE_RECEIVED: 'chat:message_received',
  VOLUNTEER_LOCATION_UPDATE: 'volunteer:location_update',
  VOLUNTEER_LOCATION_BROADCAST: 'volunteer:location_broadcast',
  NOTIFICATION_CREATED: 'notification:created',
};
