export const NOTIFICATION_TYPES = {
  RESCUE_CREATED: 'RESCUE_CREATED',
  DONATION_RECEIVED: 'DONATION_RECEIVED',
  VOLUNTEER_ASSIGNED: 'VOLUNTEER_ASSIGNED',
  ESCALATION_ALERT: 'ESCALATION_ALERT',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
};
